---
title: "Assignment 2"
author: "Nik Sassen u0403454"
date: "5/31/22"
output:
  html_document:
    number_sections: yes
    toc: yes
    fig_width: 25
    fig_height: 15
chunk_output_type: console
---
```{r setup, echo=FALSE}
# Load Packages
suppressPackageStartupMessages(library(rmarkdown))
suppressPackageStartupMessages(suppressWarnings(library(C50)))
suppressPackageStartupMessages(suppressWarnings(library(caret)))
suppressPackageStartupMessages(suppressWarnings(library(rminer)))
library(ggplot2)

```


# Code Chunk 1 - Set Up & Exploration
```{r code chunk 1}
# 1.A
# Set working directory
mydir <- getwd()
setwd(mydir)
# Import Data
d <- read.csv("CD_additional_balanced.csv")
# Overall Structure
str(d)

# 1.B
# Factor Character Variables
d$job <- factor(d$job)
d$marital <- factor(d$marital)
d$education <- factor(d$education)
d$default <- factor(d$default)
d$housing <- factor(d$housing)
d$loan <- factor(d$loan)
d$contact <- factor(d$contact)
d$month <- factor(d$month)
d$day_of_week <- factor(d$day_of_week)
d$poutcome <- factor(d$poutcome)
d$y <- factor(d$y)
# Overall Structure & Summary
str(d)
summary(d)
```


# Code Chunk 2 - Target Variable
```{r target variable}
# 2
# Count of Instances
y.table <- table(d$y)
y.table
# Proportion of Instances
y.prop <- prop.table(y.table)
y.prop

```

# Code Chunk 3 - Data Preparation
```{r data preparation}
# 3.A
# Partition data set
set.seed(100)
train <- createDataPartition(d$y, p = 0.7, list = FALSE)
dtrain <- d[train,]
dtest <- d[-train,]
# 3.B
# Distribution of train & test sets
# Train data set
table(dtrain$y)
prop.table(table(dtrain$y))
# Test data set
table(dtest$y)
prop.table(table(dtest$y))
```


# Code Chunk 4 - Train and Test Decision Tree 1 to Classify y
```{r train and test decision tree 1}
# 4.A
# Train C5.0 Model
d.c50 <- C5.0(dtrain$y~., dtrain)
d.c50
summary(d.c50)
# 4.B
# Predict Summary
predict.y <- predict(d.c50, dtest)
summary(predict.y)
# Confusion Matrix
mmetric(dtest$y, predict.y, metric = "CONF")

```


# Code Chunk 5 - Train and Test Decision Tree 2 to Classify y
```{r train and test decision tree 2}
# 5.A
# New Model with CF = 1
d.c502 <- C5.0(dtrain$y~., dtrain, control = C5.0Control(CF=1))
d.c502
summary(d.c502)
plot(d.c502)
# 5.B
# Compare Confusion Matrices and classification evaluation metrics
predicted.y <- predict(d.c502, dtest)
summary(predicted.y)
mmetric(dtest$y, predicted.y, metric = "CONF")
```


# Code Chunk 6 - Train and Test Decision Tree 3 to Predict Y
```{r train and test decision tree 3}
# 6.A
# New Decision Tree without duration
d.c503 <- C5.0(dtrain[c(-11, -21)], dtrain$y)
d.c503
summary(d.c503)
# 6.B
# Compare Confusion Matrices and classification evaluation metrics
predicted.y2 <- predict(d.c503, dtest)
summary(predicted.y2)
mmetric(dtest$y, predicted.y2, metric = "CONF")

```


# Code Chunk 7 - Train and Test Decision Tree 4 to Classify y
```{r train and test decision tree 4}
# 7.A
# New Decision Tree without duration & CF
d.c504 <- C5.0(dtrain[c(-11, -21)], dtrain$y, control = C5.0Control(CF=1))
d.c504
summary(d.c504)
plot(d.c504)
# 7.B
# Compare Confusion Matrices and classification evaluation metrics
predicted.y3 <- predict(d.c504, dtest)
summary(predicted.y3)
mmetric(dtest$y, predicted.y3, metric = "CONF")

```


# Code Chunk 8 - Visualization
```{r visualization}
ggplot(data=d) +
geom_col(aes(x=month, y=y), color="Blue") +
theme_minimal()


``` 





